### ISSUE TITLE
Installing via pallet - examples do not function

### ISSUE THREAD

**Issue by Noodleyman** [bartbutenaers/node-red-contrib-ui-heatmap#1]
after installing via the pallet, restarting node-red and trying the copy/paste code example, the map doesn't generate. 

Not sure if I am missing something?

![image](https://user-images.githubusercontent.com/10614018/53957748-19697a00-40d7-11e9-937f-4e23e8ed0661.png)

**Comment by bartbutenaers** [comment]
Hey @Noodleyman,

I see two possible causes:
+ Perhaps you are running an older dashboard version.  Minimum version **2.10.0** is required, to support custom UI nodes...
+ Perhaps you can see following error in your browser console log:

   ![image](https://user-images.githubusercontent.com/14224149/53995960-0e463680-4137-11e9-9642-5835686524c6.png)

   This is an error that I now get (for the first time ...) when I install it on one of my Raspberries.  Will have to analyze that one further ...

Bart

**Comment by Noodleyman** [comment]
Morning @bartbutenaers , 

Thanks for your feedback. The version of dashboard installed is 2.13.2.

You are correct, I did note a console warning. I should have picked up on that sooner :/

![image](https://user-images.githubusercontent.com/10614018/54023857-f057f080-418d-11e9-9a93-1f4c9eb61dc3.png)

I'm guessing some sort of permission

**Comment by bartbutenaers** [comment]
Hi @Noodleyman,

After this [discussion](https://discourse.nodered.org/t/red-httpnode-get-gives-unauthorized/8749) on the Node-RED forum, it is hopefully solved.

I have published a new **1.1.0** version on NPM.
Would be nice if you could test it and give me feedback ...

**Comment by Noodleyman** [comment]
Confirmed working, thank you. this will be a really great addition to my project. thank you for your efforts.

**Comment by bartbutenaers** [comment]
Thanks for your feedback!
