### ISSUE TITLE
Specify grid size dynamically

### ISSUE THREAD

**Issue by greyser83** [bartbutenaers/node-red-contrib-ui-heatmap#4]
![image](https://user-images.githubusercontent.com/49680277/109463379-f54a9480-7a75-11eb-9cc3-9b5777e7676d.png)
Hi Bart!
Please, tell if there is any chance to specify grid size by msg objext values.

**Comment by bartbutenaers** [comment]
Hi @greyser83,
This feature is not available yet, but after a quick look at the code I 'think' it is not a big change.
So assume that (besides `msg.payload`) there will also be an `msg.rows` and `msg.columns` that override the config screen settings.  That is not really 100% like the Node-RED convention works, but I don't have much time to spend on this feature..
Bart

**Comment by greyser83** [comment]
Ok, Bart, thanks. 
Please, suggest this issue as а request of a feature.

**Comment by bartbutenaers** [comment]
@greyser83,
With the Github version you can now specify ´msg.rows´ and `msg.columns` in the input messages.
You can install this version by executing following command from within your .node-red folder:
```
npm install bartbutenaers/node-red-contrib-ui-heatmap
```
Would be nice if you could test it, before I publish it on NPM.

**Comment by greyser83** [comment]
Hallo, Bart!
It works now, thank you!

**Comment by bartbutenaers** [comment]
Hi @greyser83,
This feature has been published on npm now, in version ***2.2.0***.
Thanks for testing!!
Bart
